/Users/ramazanhanaev/Desktop/instagram_telegram_bot_beckap/instagram_telegram_bot_reserv/fresh_env/lib/python3.12/site-packages/telegram/utils/request.py:49: UserWarning: python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.
  warnings.warn(
/Users/ramazanhanaev/Desktop/instagram_telegram_bot_beckap/instagram_telegram_bot_reserv/fresh_env/lib/python3.12/site-packages/apscheduler/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
2025-08-01 14:32:59,280 - __main__ - INFO - Инициализация базы данных...
2025-08-01 14:32:59,283 - database.db_manager - INFO - База данных инициализирована
2025-08-01 14:32:59,283 - __main__ - INFO - Запуск планировщика задач...
2025-08-01 14:32:59,283 - utils.scheduler - INFO - Планировщик задач запущен
2025-08-01 14:32:59,283 - __main__ - INFO - Запуск обработчика очереди задач...
2025-08-01 14:32:59,283 - utils.task_queue - INFO - 🚀 Запущен адаптивный обработчик очереди задач
2025-08-01 14:32:59,283 - utils.task_queue - INFO - Запущен поток обработки очереди задач
2025-08-01 14:32:59,283 - __main__ - INFO - Запуск мониторинга системных ресурсов...
2025-08-01 14:32:59,283 - utils.system_monitor - INFO - 🖥️ Запущен мониторинг системных ресурсов (профиль: macbook)
2025-08-01 14:32:59,283 - __main__ - INFO - Запуск умного валидатора аккаунтов...
2025-08-01 14:32:59,286 - utils.smart_validator_service - INFO - 🚀 Инициализирован умный валидатор (проверки: 2, восстановления: 1)
2025-08-01 14:32:59,287 - utils.smart_validator_service - INFO - ✅ Умный валидатор запущен
2025-08-01 14:32:59,287 - __main__ - INFO - Запуск Telegram бота...
2025-08-01 14:32:59,288 - py.warnings - WARNING - /Users/ramazanhanaev/Desktop/instagram_telegram_bot_beckap/instagram_telegram_bot_reserv/fresh_env/lib/python3.12/site-packages/telegram/ext/conversationhandler.py:287: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
  warnings.warn(

2025-08-01 14:32:59,316 - telegram_bot.bot - INFO - Бот настроен и готов к работе
2025-08-01 14:32:59,317 - apscheduler.scheduler - INFO - Scheduler started
2025-08-01 14:32:59,672 - __main__ - INFO - Бот запущен и готов к работе!
2025-08-01 14:33:01,298 - utils.task_queue - INFO - 🔧 Адаптация нагрузки: потоков 50 → 4 | Уровень: Стандартная активность бота
2025-08-01 14:33:02,299 - utils.system_monitor - INFO - 🖥️ 🟡 НАГРУЗКА СИСТЕМЫ: 44% (УМЕРЕННАЯ) - Стандартная активность бота | CPU: 21.5% | RAM: 82.5% | Temp: N/A
2025-08-01 14:37:52,741 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:37:52,742 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:37:52,745 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:37:57,888 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:37:57,888 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:37:57,889 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:00,031 - telegram_bot.bot - WARNING - Необработанный callback_data: bulk_add_accounts
2025-08-01 14:38:01,682 - telegram_bot.bot - WARNING - Необработанный callback_data: bulk_add_accounts
2025-08-01 14:38:03,112 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:03,113 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:03,114 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:06,173 - telegram_bot.bot - WARNING - Необработанный callback_data: bulk_add_accounts
2025-08-01 14:38:08,255 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:08,256 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:08,257 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:13,890 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:13,891 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:13,892 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:20,789 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-01 14:38:20,789 - __main__ - ERROR - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
2025-08-01 14:38:20,790 - telegram_bot.bot - ERROR - Ошибка при обработке обновления None: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
